### ISSUE TITLE
Suggestion/Request - Zombie Villagers not burning in the sun

### ISSUE THREAD

**Issue by katubug** [quat1024/zombievillagecontrol#2]
Hi! I'm really sorry, I know this is a bit out of scope for this mod, but I thought I'd at least ask. I'm using your mod to convert all of my villages into zombie villages. However, a lot of them spawn outside or wander around outside, and as such most of them just die right away, which kind of ruins the effect I was hoping for.

If it wouldn't be too difficult, a config option to make zombie villagers immune to burning in the sun would be a perfect solution for me. However, I completely understand if this is something you'd rather not to, for any reason.

Thank you very much for this mod in any case, and for your time taken to read this. <3 Hope you're having a good new year so far!

**Comment by quat1024** [comment]
Hmm, true, this is a really silly thing about the vanilla zombie villages. They didn't even fix it in 1.14 with the totally overhauled village system...

Not sure how tricky this will be, I'll take a look. Sorry for the delay.

**Comment by quat1024** [comment]
Turns out: super easy!

**Comment by quat1024** [comment]
Try this: https://www.curseforge.com/minecraft/mc-mods/zombie-village-control/files/2863066

Note that the feature is off by default, because it affects all zombie villagers in the world and not just natural spawns. Maybe someday I'll figure out how to tell the difference between the two.

**Comment by katubug** [comment]
Awesome, thank you! And having them all be sun-immune is fine with me. :) Thanks again!

**Comment by katubug** [comment]
Just wanted to pop back and say thank you another time. Just tested it, and it works perfectly! <3
